<a href="https://colab.research.google.com/github/dodamhaee/CV-anomaly-detection-algorithm/blob/main/classify_img.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import os
import shutil
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
%cd drive/MyDrive/Dacon

/content/drive/MyDrive/Dacon

In [4]:
df = pd.read_csv('train_df.csv')



---


### **각 class에 해당하는 state의 csv 생성**


---

In [90]:
state = df.copy()
state = df[['class', 'state', 'file_name']]
state

           class state  file_name
0     transistor  good  10000.png
1        capsule  good  10001.png
2     transistor  good  10002.png
3           wood  good  10003.png
4         bottle  good  10004.png
...          ...   ...        ...
4272  transistor  good  14272.png
4273  transistor  good  14273.png
4274        grid  good  14274.png
4275      zipper  good  14275.png
4276       screw  good  14276.png

[4277 rows x 3 columns]

In [91]:
state = state.sort_values(['class', 'state'])
state

       class           state  file_name
204   bottle    broken_large  10204.png
260   bottle    broken_large  10260.png
712   bottle    broken_large  10712.png
839   bottle    broken_large  10839.png
912   bottle    broken_large  10912.png
...      ...             ...        ...
1496  zipper  squeezed_teeth  11496.png
1700  zipper  squeezed_teeth  11700.png
3187  zipper  squeezed_teeth  13187.png
3647  zipper  squeezed_teeth  13647.png
3731  zipper  squeezed_teeth  13731.png

[4277 rows x 3 columns]

In [ ]:
state.to_csv('state.csv', index=False)



---


### **각 class에 해당하는 file name들의 list 생성**


---

In [ ]:
df = df[['class', 'file_name']]
df

           class  file_name
0     transistor  10000.png
1        capsule  10001.png
2     transistor  10002.png
3           wood  10003.png
4         bottle  10004.png
...          ...        ...
4272  transistor  14272.png
4273  transistor  14273.png
4274        grid  14274.png
4275      zipper  14275.png
4276       screw  14276.png

[4277 rows x 2 columns]

In [ ]:
df = df.sort_values(['class', 'file_name'])
df

       class  file_name
4     bottle  10004.png
26    bottle  10026.png
53    bottle  10053.png
58    bottle  10058.png
60    bottle  10060.png
...      ...        ...
4240  zipper  14240.png
4242  zipper  14242.png
4243  zipper  14243.png
4244  zipper  14244.png
4275  zipper  14275.png

[4277 rows x 2 columns]

In [ ]:
# class가 bottle인 경우의 file name 추출
bottle = df.loc[df['class'] == 'bottle', ['file_name']]
bottle

      file_name
4     10004.png
26    10026.png
53    10053.png
58    10058.png
60    10060.png
...         ...
4174  14174.png
4179  14179.png
4200  14200.png
4236  14236.png
4271  14271.png

[241 rows x 1 columns]

In [ ]:
# bottle의 file name list화
bottle = bottle['file_name'].values
bottle

In [ ]:
# cable의 file name list화
cable = df.loc[df['class'] == 'cable', ['file_name']]['file_name'].values
cable

In [ ]:
# capsule의 file name list화
capsule = df.loc[df['class'] == 'capsule', ['file_name']]['file_name'].values
capsule

In [ ]:
# carpet의 file name list화
carpet = df.loc[df['class'] == 'carpet', ['file_name']]['file_name'].values
carpet

In [ ]:
# grid의 file name list화
grid = df.loc[df['class'] == 'grid', ['file_name']]['file_name'].values
grid

In [ ]:
# hazelnut의 file name list화
hazelnut = df.loc[df['class'] == 'hazelnut', ['file_name']]['file_name'].values
hazelnut

In [ ]:
# leather의 file name list화
leather = df.loc[df['class'] == 'leather', ['file_name']]['file_name'].values
leather

In [ ]:
# metal_nut의 file name list화
metal_nut = df.loc[df['class']=='metal_nut', ['file_name']]['file_name'].values
metal_nut

In [ ]:
# pill의 file name list화
pill = df.loc[df['class']=='pill', ['file_name']]['file_name'].values
pill

In [ ]:
screw = df.loc[df['class']=='screw', ['file_name']]['file_name'].values
screw

In [ ]:
# tile의 file name list화
tile = df.loc[df['class']=='tile', ['file_name']]['file_name'].values
tile

In [ ]:
# toothbrush의 file name list화
toothbrush = df.loc[df['class']=='toothbrush', ['file_name']]['file_name'].values
toothbrush

In [ ]:
# transistor의 file name list화
transistor = df.loc[df['class']=='transistor', ['file_name']]['file_name'].values
transistor

In [ ]:
# wood의 file name list화
wood = df.loc[df['class']=='wood', ['file_name']]['file_name'].values
wood

In [ ]:
# zipper의 file name list화
zipper = df.loc[df['class']=='zipper', ['file_name']]['file_name'].values
zipper



---


### **각 class에 해당하는 img 분류**


---

In [ ]:
path = './train/'
file_list = os.listdir(path)

file_list.sort()
print('train datasets :', len(file_list))

train datasets : 4277

In [ ]:
# bottle 분류
for i in bottle:
  for j in file_list:
    if i > j: continue 
    if i == j:
      print(i)
      shutil.move(path + i, './classes/bottle/')

In [ ]:
# cable 분류
for i in cable:
  for j in file_list:
    if i > j: continue 
    if i == j:
      print(i)
      shutil.move(path + i, './classes/cable/')

In [ ]:
# capsule 분류
for i in capsule:
  for j in file_list:
    if i > j: continue 
    if i == j:
      print(i)
      shutil.move(path + i, './classes/capsule/')

In [ ]:
# carpet 분류
for i in carpet:
  for j in file_list:
    if i > j: continue 
    if i == j:
      print(i)
      shutil.move(path + i, './classes/carpet/')

In [ ]:
# grid 분류
for i in grid:
  for j in file_list:
    if i > j: continue 
    if i == j:
      print(i)
      shutil.move(path + i, './classes/grid/')

In [ ]:
# hazelnut 분류
for i in hazelnut:
  for j in file_list:
    if i > j: continue 
    if i == j:
      print(i)
      shutil.move(path + i, './classes/hazelnut/')

In [ ]:
# leather 분류
for i in leather:
  for j in file_list:
    if i > j: continue 
    if i == j:
      print(i)
      shutil.move(path + i, './classes/leather/')

In [ ]:
# metal_nut 분류
for i in metal_nut:
  for j in file_list:
    if i > j: continue 
    if i == j:
      print(i)
      shutil.move(path + i, './classes/metal_nut/')

In [ ]:
# pill 분류
for i in pill:
  for j in file_list:
    if i > j: continue 
    if i == j:
      print(i)
      shutil.move(path + i, './classes/pill/')

In [ ]:
# screw 분류
for i in screw:
  for j in file_list:
    if i > j: continue 
    if i == j:
      print(i)
      shutil.move(path + i, './classes/screw/')

In [ ]:
# tile 분류
for i in tile:
  for j in file_list:
    if i > j: continue 
    if i == j:
      print(i)
      shutil.move(path + i, './classes/tile/')

In [ ]:
# toothbrush 분류
for i in toothbrush:
  for j in file_list:
    if i > j: continue 
    if i == j:
      print(i)
      shutil.move(path + i, './classes/toothbrush/')

In [ ]:
# transistor 분류
for i in transistor:
  for j in file_list:
    if i > j: continue 
    if i == j:
      print(i)
      shutil.move(path + i, './classes/transistor/')

In [ ]:
# wood 분류
for i in wood:
  for j in file_list:
    if i > j: continue 
    if i == j:
      print(i)
      shutil.move(path + i, './classes/wood/')

In [ ]:
# zipper 분류
for i in zipper:
  for j in file_list:
    if i > j: continue 
    if i == j:
      print(i)
      shutil.move(path + i, './classes/zipper/')